let lastName = "Smith";
let name = 'John';
let freeSpace = ' ';
let city = 'Berlin';
let ege = '43';
let job = 'Teacher';
console.log(name, freeSpace, lastName);
console.log('City' + freeSpace + city);
console.log('Ege'+ freeSpace + ege);
console.log('Job'+ freeSpace + job);
console.log(name + ' ' + lastName + ' is a ' + ege + ' old ' + ' ' + job + ' who lives in ' + city);